import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { type Metadata } from "next";

const inter = Inter({
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
    return (
        <nav className="flex items-center justify-between w-full p-4 text-xl font-semibold border-b">
            <div>T3 Gallery</div>
            <div>Sign In</div>
        </nav>
    )
}
export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`font-sans ${inter.className} flex flex-col gap-4`}>
            <body>
                <TopNav />
                {children}
            </body>
        </html>
    );
}
